// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pacG15lBddeB7MO2IdaAAnI5uigSE3I',
    appId: '1:888451958802:web:e04b4b0fbd68d0102ef0cb',
    messagingSenderId: '888451958802',
    projectId: 'rightnow-chat-app',
    authDomain: 'rightnow-chat-app.firebaseapp.com',
    storageBucket: 'rightnow-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdhcDbFqcHDy776hxwXMDShiAs6c5rFw',
    appId: '1:888451958802:android:dabbccb2f50121422ef0cb',
    messagingSenderId: '888451958802',
    projectId: 'rightnow-chat-app',
    storageBucket: 'rightnow-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNKIz1lcRXNdjhGhgwLheWjxZ22q2P80',
    appId: '1:888451958802:ios:421c20537c7ab1262ef0cb',
    messagingSenderId: '888451958802',
    projectId: 'rightnow-chat-app',
    storageBucket: 'rightnow-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNKIz1lcRXNdjhGhgwLheWjxZ22q2P80',
    appId: '1:888451958802:ios:421c20537c7ab1262ef0cb',
    messagingSenderId: '888451958802',
    projectId: 'rightnow-chat-app',
    storageBucket: 'rightnow-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );
}